"""Evolving episodes with exact ground truth.

An episode is a task (predicates, gates, actions) plus a sequence of evidence events. The text is
real: claims and evidence come from atoms (ease/data/atoms.py). The structure and the ground truth
are generated by rule:

  * which record bears on which predicate is known because the generator attached it;
  * what a record establishes is the human label of its atom;
  * which record prevails is the declared policy, highest authority first, then latest validity;
  * requirement statuses follow from three-valued logic; action outcomes are sampled from the
    hidden truth with the action's declared reliability.

No language model assigns any label or probability.

Records attached to different predicates come from different source pages, and every other
(record, predicate) pair is treated as unrelated. That assumption is what lets the generator
label those pairs; it also means distractors here are topically unrelated, which is an easier
case than same-topic distractors. Same-topic hard negatives appear only as VitaminC evidence
versions labelled NEI.
"""

from __future__ import annotations

import random
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Optional

from ease.labels import NEI, SUPPORTS
from ease.ledger import Event, Ledger, Status
from ease.logic import SATISFIED, UNRESOLVED, VIOLATED, status_of, truth_of
from ease.schema import AND, ATLEAST, NOT, OR, Action, Gate, Predicate, TaskSchema

CONFLICT = 3  # predicate-level only: top-ranked decisive records disagree
PRED_STATUS_NAMES = ("SATISFIED", "VIOLATED", "UNRESOLVED", "CONFLICT")
READY, BLOCKED, NEEDS_INFO = "READY", "BLOCKED", "NEEDS_INFO"
DISPOSITION = {SATISFIED: READY, VIOLATED: BLOCKED, UNRESOLVED: NEEDS_INFO}

SOURCES = (("client", 2), ("team", 1), ("vendor", 1), ("import", 0))

# SNLI labels assume premise and hypothesis describe the same scene (see ease/data/sources.py), so
# its "contradiction" is not a statement about evidence. It is kept out of episode ground truth.
EXCLUDED_ATOM_SOURCES = ("snli",)


@dataclass
class GenConfig:
    n_pred: tuple[int, int] = (3, 8)
    p_revision_atom: float = 0.65
    p_initial_evidence: float = 0.7
    n_distractors: tuple[int, int] = (0, 8)
    n_events: tuple[int, int] = (6, 14)
    n_actions: tuple[int, int] = (1, 3)
    max_children: int = 3
    p_not: float = 0.15
    p_share: float = 0.25
    p_rank_tie: float = 0.35  # a second source asserts the same effective time at the same authority
    event_probs: dict = field(default_factory=lambda: {
        "revise": 0.30, "add": 0.14, "retract": 0.12, "duplicate": 0.10, "stale": 0.08,
        "distractor": 0.12, "second_source": 0.09, "conflict_same_rev": 0.03, "reinstate": 0.02,
    })


class AtomIndex:
    def __init__(self, atoms: list[dict], exclude_sources: tuple[str, ...] = EXCLUDED_ATOM_SOURCES):
        atoms = [a for a in atoms if a["source"] not in exclude_sources]
        self.revision = [a for a in atoms if a["kind"] == "revision"]
        self.static = [a for a in atoms if a["kind"] == "static"]
        self.all = atoms

    def draw(self, rng: random.Random, n: int, p_revision: float, used_pages: set[str]) -> list[dict]:
        out = []
        guard = 0
        while len(out) < n:
            guard += 1
            if guard > 50 * n + 1000:
                raise RuntimeError("atom pool too small for the requested episode")
            pool = self.revision if (rng.random() < p_revision and self.revision) else self.static
            a = pool[rng.randrange(len(pool))]
            if a["page"] in used_pages:
                continue
            used_pages.add(a["page"])
            out.append(a)
        return out


def _build_formula(rng: random.Random, leaves: list[str], cfg: GenConfig, gates: list[Gate], prefix: str) -> str:
    """Random formula tree over `leaves`; returns the id of its root. Each leaf is used once."""
    nodes = []
    for leaf in leaves:
        if rng.random() < cfg.p_not:
            gid = f"{prefix}n{len(gates)}"
            gates.append(Gate(gid, NOT, (leaf,)))
            nodes.append(gid)
        else:
            nodes.append(leaf)
    while len(nodes) > 1:
        rng.shuffle(nodes)
        size = rng.randint(2, min(cfg.max_children, len(nodes)))
        kids, nodes = nodes[:size], nodes[size:]
        op = rng.choice([AND, AND, OR, ATLEAST])
        k = rng.randint(1, size) if op == ATLEAST else 0
        gid = f"{prefix}g{len(gates)}"
        gates.append(Gate(gid, op, tuple(kids), k))
        nodes.append(gid)
    return nodes[0]


def predicate_status(active: dict, gold: dict, pid: str) -> int:
    """Declared policy applied to gold labels: decisive records only; highest authority, then latest
    validity; disagreement at the top rank is a conflict."""
    decisive = []
    for rid, payload in active.items():
        g = gold.get((rid, payload.key))
        if g is None or g[0] != pid or g[1] == NEI:
            continue
        decisive.append(((payload.authority, payload.valid_from if payload.valid_from is not None else float("-inf")), g[1]))
    if not decisive:
        return UNRESOLVED
    top = max(r for r, _ in decisive)
    labels = {l for r, l in decisive if r == top}
    if len(labels) > 1:
        return CONFLICT
    return SATISFIED if labels.pop() == SUPPORTS else VIOLATED


def generate_episode(index: AtomIndex, seed: int, cfg: GenConfig, episode_id: str) -> dict:
    rng = random.Random(seed)
    used_pages: set[str] = set()
    m = rng.randint(*cfg.n_pred)
    atoms = index.draw(rng, m, cfg.p_revision_atom, used_pages)
    preds = [Predicate(f"p{j}", a["claim"], prior=rng.choice([0.2, 0.5, 0.8]), ask_cost=rng.choice([0.5, 1.0, 2.0]))
             for j, a in enumerate(atoms)]
    atom_of = {p.id: a for p, a in zip(preds, atoms)}

    # actions and their requirement formulas
    k = min(rng.randint(*cfg.n_actions), m)
    ids = [p.id for p in preds]
    rng.shuffle(ids)
    parts = [[ids[i]] for i in range(k)]
    for pid in ids[k:]:
        parts[rng.randrange(k)].append(pid)
    gates: list[Gate] = []
    actions: list[Action] = []
    for ai, part in enumerate(parts):
        extra = [p for p in ids if p not in part and rng.random() < cfg.p_share / max(1, m)]
        root = _build_formula(rng, part + extra, cfg, gates, f"a{ai}")
        actions.append(Action(f"act{ai}", f"action {ai}", root,
                              value_success=rng.choice([1.0, 2.0, 5.0]), cost_failure=rng.choice([1.0, 3.0, 10.0]),
                              reliability=rng.choice([1.0, 0.95, 0.9]), leak=rng.choice([0.0, 0.0, 0.05])))
    schema = TaskSchema(episode_id, preds, gates, actions)
    hidden = {p.id: rng.random() < p.prior for p in preds}

    led = Ledger()
    gold: dict[tuple[str, str], tuple[Optional[str], int]] = {}
    delivered: dict[str, list[Event]] = defaultdict(list)
    version_of: dict[str, int] = {}  # record_id -> index of the evidence version currently asserted
    link: dict[str, Optional[str]] = {}
    clock = [0.0]
    n_distractors = [0]
    steps: list[dict] = []
    prev_pred: dict[str, int] = {}
    prev_disp: dict[str, str] = {}

    def tick() -> float:
        clock[0] += 1.0
        return clock[0]

    def truth_now() -> dict:
        active = led.active()
        ps = {p.id: predicate_status(active, gold, p.id) for p in preds}
        leaf3 = {pid: (UNRESOLVED if s == CONFLICT else s) for pid, s in ps.items()}
        leaf_truth = {pid: (True if s == SATISFIED else False if s == VIOLATED else hidden[pid]) for pid, s in ps.items()}
        node = {g.id: status_of(schema, g.id, leaf3) for g in gates}
        acts = {}
        for a in actions:
            s = status_of(schema, a.requires, leaf3)
            t = truth_of(schema, a.requires, leaf_truth)
            acts[a.id] = {"status": s, "disposition": DISPOSITION[s], "holds": t,
                          "success": rng.random() < (a.reliability if t else a.leak)}
        return {"pred": ps, "node": node, "actions": acts, "n_active": len(active)}

    def record(kind: str, ev: Event, target: Optional[str], label: Optional[int], setup: bool) -> None:
        receipt = led.deliver(ev)
        delivered[ev.record_id].append(ev)
        tr = truth_now()
        tr["changed_preds"] = [pid for pid, s in tr["pred"].items() if prev_pred.get(pid, UNRESOLVED) != s]
        tr["changed_actions"] = [aid for aid, a in tr["actions"].items() if prev_disp.get(aid, NEEDS_INFO) != a["disposition"]]
        prev_pred.update(tr["pred"])
        prev_disp.update({aid: a["disposition"] for aid, a in tr["actions"].items()})
        steps.append({
            "t": len(steps), "type": kind, "setup": setup,
            "event": {"record_id": ev.record_id, "revision": ev.revision, "text": ev.text, "source_id": ev.source_id,
                      "authority": ev.authority, "valid_from": ev.valid_from},
            "target_pred": target, "gold_relation": label,
            "ledger_outcome": receipt.outcome.value, "ledger_changed": receipt.changed,
            "truth": tr,
        })

    def evidence_event(rid: str, revision: int, pid: str, vi: int, source: tuple[str, int],
                       valid_from: Optional[float] = None) -> tuple[Event, int]:
        v = atom_of[pid]["versions"][vi]
        ev = Event(rid, revision, v["text"], source_id=source[0], authority=source[1],
                   valid_from=tick() if valid_from is None else valid_from)
        gold[(rid, ev.payload_key())] = (pid, v["label"])
        version_of[rid] = vi
        link[rid] = pid
        return ev, v["label"]

    def distractor_event() -> Event:
        a = index.draw(rng, 1, 0.5, used_pages)[0]
        rid = f"rec_d{n_distractors[0]}"
        n_distractors[0] += 1
        src = rng.choice(SOURCES)
        ev = Event(rid, 1, rng.choice(a["versions"])["text"], source_id=src[0], authority=src[1], valid_from=tick())
        gold[(rid, ev.payload_key())] = (None, NEI)
        link[rid] = None
        return ev

    # ---- setup: the initial state of the task
    for p in preds:
        if rng.random() < cfg.p_initial_evidence:
            src = rng.choice(SOURCES)
            vi = rng.randrange(len(atom_of[p.id]["versions"]))
            ev, lab = evidence_event(f"rec_{p.id}_{src[0]}", 1, p.id, vi, src)
            record("add", ev, p.id, lab, True)
    for _ in range(rng.randint(*cfg.n_distractors)):
        record("distractor", distractor_event(), None, None, True)

    # ---- the evolving part
    kinds, probs = zip(*cfg.event_probs.items())
    target_events = rng.randint(*cfg.n_events)
    attempts = 0
    while sum(1 for s in steps if not s["setup"]) < target_events and attempts < 40 * target_events:
        attempts += 1
        kind = rng.choices(kinds, weights=probs, k=1)[0]
        states = led.records()
        active = led.active()
        if kind == "revise":
            cands = [rid for rid in active if link.get(rid) and len(atom_of[link[rid]]["versions"]) >= 2]
            if not cands:
                continue
            rid = rng.choice(sorted(cands))
            pid = link[rid]
            src = (active[rid].source_id, active[rid].authority)
            ev, lab = evidence_event(rid, states[rid].revision + 1, pid, 1 - version_of[rid], src)
            record(kind, ev, pid, lab, False)
        elif kind == "add":
            have = {link[r] for r in states if link.get(r)}
            cands = [p.id for p in preds if p.id not in have]
            if not cands:
                continue
            pid = rng.choice(cands)
            src = rng.choice(SOURCES)
            ev, lab = evidence_event(f"rec_{pid}_{src[0]}", 1, pid, rng.randrange(len(atom_of[pid]["versions"])), src)
            record(kind, ev, pid, lab, False)
        elif kind == "retract":
            if not active:
                continue
            rid = rng.choice(sorted(active))
            record(kind, Event(rid, states[rid].revision + 1, None, source_id=active[rid].source_id,
                               authority=active[rid].authority), link.get(rid), None, False)
        elif kind == "duplicate":
            cands = [rid for rid in delivered if delivered[rid] and states[rid].stored_status is not Status.CONFLICTED]
            if not cands:
                continue
            rid = rng.choice(sorted(cands))
            top = [e for e in delivered[rid] if e.revision == states[rid].revision]
            record(kind, top[-1], link.get(rid), None, False)
        elif kind == "stale":
            cands = [rid for rid in delivered if any(e.revision < states[rid].revision for e in delivered[rid])]
            if not cands:
                continue
            rid = rng.choice(sorted(cands))
            old = [e for e in delivered[rid] if e.revision < states[rid].revision]
            record(kind, rng.choice(old), link.get(rid), None, False)
        elif kind == "distractor":
            record(kind, distractor_event(), None, None, False)
        elif kind == "second_source":
            cands = [rid for rid in active if link.get(rid) and len(atom_of[link[rid]]["versions"]) >= 2]
            if not cands:
                continue
            rid = rng.choice(sorted(cands))
            pid = link[rid]
            others = [s for s in SOURCES if f"rec_{pid}_{s[0]}" not in states]
            if not others:
                continue
            peers = [s for s in others if s[1] == active[rid].authority]
            if peers and rng.random() < cfg.p_rank_tie:
                # same authority, same effective time: if the two disagree, neither prevails
                src = rng.choice(peers)
                ev, lab = evidence_event(f"rec_{pid}_{src[0]}", 1, pid, rng.randrange(2), src,
                                         valid_from=active[rid].valid_from)
            else:
                src = rng.choice(others)
                ev, lab = evidence_event(f"rec_{pid}_{src[0]}", 1, pid, rng.randrange(2), src)
            record(kind, ev, pid, lab, False)
        elif kind == "conflict_same_rev":
            cands = [rid for rid in active if link.get(rid) and len(atom_of[link[rid]]["versions"]) >= 2]
            if not cands:
                continue
            rid = rng.choice(sorted(cands))
            pid = link[rid]
            keep = version_of[rid]
            v = atom_of[pid]["versions"][1 - keep]
            ev = Event(rid, states[rid].revision, v["text"], source_id=active[rid].source_id,
                       authority=active[rid].authority, valid_from=active[rid].valid_from)
            gold[(rid, ev.payload_key())] = (pid, v["label"])
            record(kind, ev, pid, v["label"], False)
        elif kind == "reinstate":
            cands = [rid for rid, st in states.items() if st.stored_status is not Status.ACTIVE and link.get(rid)]
            if not cands:
                continue
            rid = rng.choice(sorted(cands))
            pid = link[rid]
            last = delivered[rid][-1]
            ev, lab = evidence_event(rid, states[rid].revision + 1, pid,
                                     rng.randrange(len(atom_of[pid]["versions"])), (last.source_id, last.authority))
            record(kind, ev, pid, lab, False)

    led.close()
    return {
        "episode_id": episode_id,
        "seed": seed,
        "schema": schema.to_dict(),
        "hidden": hidden,
        "links": link,
        "atom_ids": {p.id: atom_of[p.id]["atom_id"] for p in preds},
        "steps": steps,
    }


def generate(atoms: list[dict], n: int, seed: int, cfg: Optional[GenConfig] = None, tag: str = "ep") -> list[dict]:
    cfg = cfg or GenConfig()
    index = AtomIndex(atoms)
    return [generate_episode(index, seed * 1_000_003 + i, cfg, f"{tag}-{seed}-{i}") for i in range(n)]


# Generator settings used in the experiments. "wide" is never seen in training.
STANDARD = GenConfig()
WIDE = GenConfig(n_pred=(9, 16), n_distractors=(10, 30), n_events=(12, 24), n_actions=(2, 5), max_children=4)


def describe(episodes: list[dict]) -> dict:
    kinds = defaultdict(int)
    outcomes = defaultdict(int)
    changed = 0
    total = 0
    statuses = defaultdict(int)
    disp = defaultdict(int)
    for ep in episodes:
        for s in ep["steps"]:
            if s["setup"]:
                continue
            total += 1
            kinds[s["type"]] += 1
            outcomes[s["ledger_outcome"]] += 1
            changed += bool(s["truth"]["changed_actions"])
            for v in s["truth"]["pred"].values():
                statuses[PRED_STATUS_NAMES[v]] += 1
            for a in s["truth"]["actions"].values():
                disp[a["disposition"]] += 1
    return {
        "episodes": len(episodes), "events": total, "event_types": dict(kinds), "ledger_outcomes": dict(outcomes),
        "events_changing_some_action": changed, "predicate_status": dict(statuses), "action_disposition": dict(disp),
        "mean_predicates": sum(len(e["schema"]["predicates"]) for e in episodes) / max(1, len(episodes)),
        "mean_records": sum(len(e["links"]) for e in episodes) / max(1, len(episodes)),
    }
